spring:
    datasource:
        password: augeAdmin123
        url: jdbc:postgresql://ip-172-31-6-64.us-east-2.compute.internal/postgres
        username: postgres
    jpa:
        generate-ddl: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
    
    
eureka:
    client:
        serviceUrl:
            defaultZone: ip-172-31-8-146.us-east-2.compute.internal:8099/eureka/
