#Application Configuration
server:
  port: 8092

spring:
    datasource:
        password: Smilodon1
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        generate-ddl: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
    
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8099/eureka/
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
